### ISSUE TITLE
[PLAN] Basic gesture recognition and interface

### ISSUE THREAD

**Issue by xjjak** [xjjak/LapCal#33]
*This is a placeholder for now.*

Ideas and plans for some neat, but "easy" features for showing off at the Jufo competition.

First thing definitely will be simple tapping or swiping for slide advancing.

**Comment by palisn** [comment]
As introduced with the first click detection, we got simple one finger tap detection.  Additionally, with the same approach we are able to get two finger click detection, though this is not very reliable yet.
