### ISSUE TITLE
[FEATURE] Live plotting of serial data

### ISSUE THREAD

**Issue by palisn** [xjjak/LapCal#51]
**Is your feature request related to a problem? Please describe.**

Due to the nature of the data, the text data is pretty much useless to human eyes. I would like some way to assess the correctness and the behavior of our input data.

**Describe the solution you'd like**
I think a simple plotting tool would suffice for this. Later on, one might extend it to include some more intuitive visualizations.

**Describe alternatives you've considered**
We had a very simple PyGame plotting utility, but it was a bit of a pain to use and not easily extendable. Also, I would like to have a very simple GUI to get the utility running quickly. Unlike the PyGame utility, which did provide little description of what it displayed and where one had to go through the source code every time just to get it to work.

**Comment by xjjak** [comment]
One additional feature I'd propose, if that's not already on some list, would be split screens or a dashboard system to view multiple plots at the same time.
